[package]
name = "temu_for_pc"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk = "0.9.0"
glib = "0.9.0"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level = 3